[package]
name = "psicogestao"
version = "0.1.0"
description = "PsicoGestão Desktop"
authors = ["PsicoGestão"]
edition = "2021"

[lib]
name = "psicogestao_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
