import { clearCookie, hashPassword, readCookie, sha256, verifyPassword } from './auth'
import { newTotpSecret, totpUri, verifyTotp } from './totp'
import type { Env } from './types'
const ADMIN_COOKIE='ps_admin_session',json=(data:unknown,status=200,headers:HeadersInit={})=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers}}),now=()=>new Date().toISOString()
async function body(r:Request){try{return await r.json() as Record<string,any>}catch{return {}}}
async function audit(env:Env,id:string,action:string,type='admin_user',entity?:string|null){await env.DB.prepare(`INSERT INTO audit_log(id,actor_type,actor_id,action,entity_type,entity_id) VALUES(?,'admin',?,?,?,?)`).bind(crypto.randomUUID(),id,action,type,entity||null).run()}
async function currentAdmin(r:Request,env:Env){const t=readCookie(r,ADMIN_COOKIE);if(!t)return null;return env.DB.prepare(`SELECT a.id,a.email,a.display_name,a.role,a.active,s.id session_id FROM admin_sessions s JOIN admin_users a ON a.id=s.admin_user_id WHERE s.token_hash=? AND s.expires_at>? AND a.active=1`).bind(await sha256(t),now()).first<any>()}
async function requireAdmin(r:Request,env:Env){const admin=await currentAdmin(r,env);return admin?{error:null,admin}:{error:json({ok:false,message:'Acesso profissional necessário.'},401),admin:null}}
async function creds(env:Env,id:string){return env.DB.prepare('SELECT password_hash,password_salt FROM admin_users WHERE id=?').bind(id).first<any>()}
export async function guardAdminRole(r:Request,env:Env,path:string){if(!path.startsWith('/api/admin/')||path.startsWith('/api/admin/security')||path.startsWith('/api/admin/users'))return null;const protectedArea=/^\/api\/admin\/patients\/\d+(?:\/notes)?$/.test(path)||path.startsWith('/api/admin/notes/')||(path==='/api/admin/settings'&&r.method!=='GET');if(!protectedArea)return null;const s=await requireAdmin(r,env);if(s.error)return s.error;return s.admin.role==='psychologist'?null:json({ok:false,message:'Seu nível de acesso não permite esta área.'},403)}
export async function handleAdminSecurity(r:Request,env:Env,path:string):Promise<Response|null>{const relevant=path.startsWith('/api/admin/security/')||path==='/api/admin/users'||/^\/api\/admin\/users\/[^/]+$/.test(path);if(!relevant)return null
if(path==='/api/admin/security/2fa'&&r.method==='GET'){const s=await requireAdmin(r,env);if(s.error)return s.error;const row=await env.DB.prepare('SELECT totp_enabled FROM admin_users WHERE id=?').bind(s.admin.id).first<any>();return json({ok:true,enabled:Number(row?.totp_enabled)===1})}
if(path==='/api/admin/security/2fa/setup'&&r.method==='POST'){const s=await requireAdmin(r,env);if(s.error)return s.error;const secret=newTotpSecret();await env.DB.prepare('UPDATE admin_users SET totp_secret=?,totp_enabled=0,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(secret,s.admin.id).run();return json({ok:true,secret,uri:totpUri(secret,s.admin.email)})}
if(path==='/api/admin/security/2fa/enable'&&r.method==='POST'){const s=await requireAdmin(r,env);if(s.error)return s.error;const b=await body(r),row=await env.DB.prepare('SELECT totp_secret FROM admin_users WHERE id=?').bind(s.admin.id).first<any>();if(!row?.totp_secret||!(await verifyTotp(row.totp_secret,String(b.code||''))))return json({ok:false,message:'Código inválido. Confira o aplicativo autenticador.'},400);await env.DB.prepare('UPDATE admin_users SET totp_enabled=1,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(s.admin.id).run();await audit(env,s.admin.id,'admin_2fa_enabled');return json({ok:true,message:'Autenticação em dois fatores ativada.'})}
if(path==='/api/admin/security/2fa/disable'&&r.method==='POST'){const s=await requireAdmin(r,env);if(s.error)return s.error;const b=await body(r),c=await creds(env,s.admin.id);if(!c||!(await verifyPassword(String(b.current_password||''),c.password_salt,c.password_hash)))return json({ok:false,message:'Senha atual incorreta.'},401);await env.DB.prepare('UPDATE admin_users SET totp_secret=NULL,totp_enabled=0,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(s.admin.id).run();await audit(env,s.admin.id,'admin_2fa_disabled');return json({ok:true,message:'Autenticação em dois fatores desativada.'})}
if(path==='/api/admin/security/sessions'&&r.method==='GET'){const s=await requireAdmin(r,env);if(s.error)return s.error;const q=await env.DB.prepare('SELECT id,created_at,expires_at FROM admin_sessions WHERE admin_user_id=? AND expires_at>? ORDER BY created_at DESC').bind(s.admin.id,now()).all<any>();return json({ok:true,sessions:(q.results||[]).map((x:any)=>({...x,current:x.id===s.admin.session_id}))})}
if(path==='/api/admin/security/sessions/others'&&r.method==='DELETE'){const s=await requireAdmin(r,env);if(s.error)return s.error;await env.DB.prepare('DELETE FROM admin_sessions WHERE admin_user_id=? AND id<>?').bind(s.admin.id,s.admin.session_id).run();return json({ok:true,message:'Outras sessões encerradas.'})}
const sm=path.match(/^\/api\/admin\/security\/sessions\/([^/]+)$/);if(sm&&r.method==='DELETE'){const s=await requireAdmin(r,env);if(s.error)return s.error;const id=decodeURIComponent(sm[1]);if(id===s.admin.session_id)return json({ok:false,message:'A sessão atual deve ser encerrada pelo botão Sair.'},409);await env.DB.prepare('DELETE FROM admin_sessions WHERE id=? AND admin_user_id=?').bind(id,s.admin.id).run();return json({ok:true,message:'Sessão encerrada.'})}
if(path==='/api/admin/security/activity'&&r.method==='GET'){const s=await requireAdmin(r,env);if(s.error)return s.error;const q=await env.DB.prepare(`SELECT id,action,entity_type,entity_id,created_at FROM audit_log WHERE actor_type='admin' AND actor_id=? ORDER BY created_at DESC LIMIT 50`).bind(s.admin.id).all<any>();return json({ok:true,events:q.results||[]})}
if(path==='/api/admin/security/email'&&r.method==='PATCH'){const s=await requireAdmin(r,env);if(s.error)return s.error;const b=await body(r),email=String(b.email||'').trim().toLowerCase(),c=await creds(env,s.admin.id);if(!email.includes('@'))return json({ok:false,message:'Informe um e-mail válido.'},400);if(!c||!(await verifyPassword(String(b.current_password||''),c.password_salt,c.password_hash)))return json({ok:false,message:'Senha atual incorreta.'},401);await env.DB.prepare('UPDATE admin_users SET email=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(email,s.admin.id).run();await audit(env,s.admin.id,'admin_email_changed');return json({ok:true,message:'E-mail de acesso atualizado.',email})}
if(path==='/api/admin/security/password'&&r.method==='PATCH'){const s=await requireAdmin(r,env);if(s.error)return s.error;const b=await body(r),next=String(b.new_password||''),c=await creds(env,s.admin.id);if(next.length<10)return json({ok:false,message:'A nova senha deve ter pelo menos 10 caracteres.'},400);if(!c||!(await verifyPassword(String(b.current_password||''),c.password_salt,c.password_hash)))return json({ok:false,message:'Senha atual incorreta.'},401);const p=await hashPassword(next);await env.DB.prepare('UPDATE admin_users SET password_hash=?,password_salt=? WHERE id=?').bind(p.hash,p.salt,s.admin.id).run();await env.DB.prepare('DELETE FROM admin_sessions WHERE admin_user_id=?').bind(s.admin.id).run();return json({ok:true,message:'Senha alterada. Entre novamente.',},200,{'set-cookie':clearCookie(ADMIN_COOKIE)})}
if(path==='/api/admin/users'&&r.method==='GET'){const s=await requireAdmin(r,env);if(s.error)return s.error;if(s.admin.role!=='psychologist')return json({ok:false,message:'Esta ação exige acesso de Psicóloga / Administrador.'},403);const q=await env.DB.prepare('SELECT id,email,display_name,role,active,created_at FROM admin_users ORDER BY active DESC,display_name').all<any>();return json({ok:true,users:q.results||[]})}
return json({ok:false,message:'Método não permitido.'},405)}
