import './admin-platform-pricing.css'

type Origin='particular'|'platform_1'|'platform_2'
type Table={key:Origin;name:string;price_cents?:number;registration_url?:string}
type Patient={id:number;full_name:string;email:string;pricing_origin?:Origin}
const money=(c:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format((Number(c)||0)/100)
async function json(path:string,init?:RequestInit){const r=await fetch(path,{credentials:'include',headers:{'content-type':'application/json',...(init?.headers||{})},...init});const d=await r.json().catch(()=>({})) as any;if(!r.ok)throw new Error(d.message||'Não foi possível concluir a ação.');return d}

let busy=false
async function mount(){
  if(busy)return
  const panel=document.querySelector<HTMLElement>('.settings-panel');if(!panel||panel.querySelector('.platform-pricing-admin'))return
  busy=true
  try{
    const [pricing,patientData]=await Promise.all([json('/api/admin/pricing-tables'),json('/api/admin/patients')])
    if(!panel.isConnected)return
    const tables=pricing.tables as Record<Origin,Table>,patients=(patientData.patients||[]) as Patient[]
    const section=document.createElement('section');section.className='platform-pricing-admin'
    section.innerHTML=`<div class="platform-pricing-head"><div><span class="section-kicker">Tabelas de preço</span><h2>Origem dos pacientes</h2><p>Cadastros comuns permanecem como <strong>Particular</strong>. Para pacientes de plataformas, envie o link exclusivo correspondente.</p></div></div><form class="platform-pricing-form"><article class="platform-price-card fixed"><div><strong>Particular</strong><small>Tabela padrão do consultório</small></div><p>Usa os valores Pix e Cartão configurados acima.</p></article>${(['platform_1','platform_2'] as Origin[]).map(origin=>{const t=tables[origin];return `<article class="platform-price-card"><label>Nome da plataforma<input name="${origin}_name" maxlength="80" required value="${String(t.name||'').replace(/"/g,'&quot;')}"></label><label>Valor por sessão (R$)<input name="${origin}_price" type="number" min="0" step="0.01" required value="${((Number(t.price_cents)||0)/100).toFixed(2)}"></label><div class="platform-link"><span>Link exclusivo de cadastro</span><input readonly value="${String(t.registration_url||'').replace(/"/g,'&quot;')}" data-link="${origin}"><div><button type="button" data-copy="${origin}">Copiar link</button><button type="button" data-regenerate="${origin}">Gerar novo link</button></div></div></article>`}).join('')}<div class="platform-actions"><button class="admin-primary" type="submit">Salvar tabelas</button><span data-platform-message></span></div></form><div class="platform-existing"><h3>Paciente já cadastrado</h3><p>Use esta opção para classificar pacientes que já possuem conta no PsicoGestão.</p><div class="platform-existing-row"><select data-patient-select><option value="">Selecione o paciente</option>${patients.map(p=>`<option value="${p.id}" data-origin="${p.pricing_origin||'particular'}">${p.full_name} — ${p.email}</option>`).join('')}</select><select data-origin-select><option value="particular">Particular</option><option value="platform_1">${tables.platform_1.name}</option><option value="platform_2">${tables.platform_2.name}</option></select><button type="button" data-save-patient>Aplicar</button></div><small data-patient-message></small></div>`
    panel.appendChild(section)
    const form=section.querySelector<HTMLFormElement>('form')!,msg=section.querySelector<HTMLElement>('[data-platform-message]')!
    form.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(form),btn=form.querySelector<HTMLButtonElement>('button[type=submit]')!;btn.disabled=true;msg.textContent='Salvando...';try{const d=await json('/api/admin/pricing-tables',{method:'PUT',body:JSON.stringify({platform_1:{name:String(fd.get('platform_1_name')||''),price_cents:Math.round(Number(fd.get('platform_1_price')||0)*100)},platform_2:{name:String(fd.get('platform_2_name')||''),price_cents:Math.round(Number(fd.get('platform_2_price')||0)*100)}})});msg.textContent=d.message||'Salvo.';setTimeout(()=>location.reload(),450)}catch(e){msg.textContent=e instanceof Error?e.message:'Erro ao salvar.'}finally{btn.disabled=false}})
    section.querySelectorAll<HTMLButtonElement>('[data-copy]').forEach(btn=>btn.addEventListener('click',async()=>{const input=section.querySelector<HTMLInputElement>(`[data-link="${btn.dataset.copy}"]`);if(!input)return;await navigator.clipboard.writeText(input.value);const old=btn.textContent;btn.textContent='Copiado!';setTimeout(()=>btn.textContent=old,1200)}))
    section.querySelectorAll<HTMLButtonElement>('[data-regenerate]').forEach(btn=>btn.addEventListener('click',async()=>{if(!confirm('O link anterior deixará de cadastrar pacientes nesta plataforma. Gerar um novo link?'))return;btn.disabled=true;try{const d=await json(`/api/admin/pricing-tables/${btn.dataset.regenerate}/regenerate-link`,{method:'POST'});const input=section.querySelector<HTMLInputElement>(`[data-link="${btn.dataset.regenerate}"]`);if(input)input.value=d.tables[btn.dataset.regenerate!].registration_url}catch(e){alert(e instanceof Error?e.message:'Não foi possível gerar o link.')}finally{btn.disabled=false}}))
    const patientSelect=section.querySelector<HTMLSelectElement>('[data-patient-select]')!,originSelect=section.querySelector<HTMLSelectElement>('[data-origin-select]')!,patientMsg=section.querySelector<HTMLElement>('[data-patient-message]')!,savePatient=section.querySelector<HTMLButtonElement>('[data-save-patient]')!
    patientSelect.addEventListener('change',()=>{const option=patientSelect.selectedOptions[0];originSelect.value=option?.dataset.origin||'particular'})
    savePatient.addEventListener('click',async()=>{if(!patientSelect.value)return;savePatient.disabled=true;patientMsg.textContent='Salvando...';try{const d=await json(`/api/admin/patients/${patientSelect.value}/pricing-origin`,{method:'PATCH',body:JSON.stringify({pricing_origin:originSelect.value})});patientSelect.selectedOptions[0].dataset.origin=originSelect.value;patientMsg.textContent=d.message||'Atualizado.'}catch(e){patientMsg.textContent=e instanceof Error?e.message:'Erro ao atualizar.'}finally{savePatient.disabled=false}})
  }catch(e){console.error('Platform pricing admin:',e)}finally{busy=false}
}

export function installAdminPlatformPricingEnhancer(){const run=()=>void mount();[0,180,500,1000].forEach(ms=>setTimeout(run,ms));const root=document.getElementById('root');if(root)new MutationObserver(()=>run()).observe(root,{childList:true,subtree:true})}
