type Appointment={id:number;status:string;workflow_state?:string|null;amount_cents:number;paid_at?:string|null;availability_id:number;starts_at:string;ends_at:string;patient_id:number;full_name:string;email:string;phone:string}
const money=(c:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format((c||0)/100)
const fmtDateTime=(v:string)=>new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(v))
const esc=(v:unknown)=>String(v??'').replace(/[&<>'"]/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[ch]||ch))
const appointmentStatus=(a:Appointment)=>a.workflow_state==='awaiting_reschedule'?'Aguardando reagendamento':a.status==='confirmed'?'Confirmada':a.status==='pending_payment'?'Aguardando pagamento':a.status==='cancelled'?'Cancelada':a.status==='expired'?'Expirada':a.status
let scheduled:number|undefined,loading=false
function findPatientCard(email:string){let attempts=0;const tryOpen=()=>{attempts++;const card=[...document.querySelectorAll<HTMLButtonElement>('.patient-card')].find(el=>(el.textContent||'').includes(email));if(card){card.click();return}if(attempts<25)setTimeout(tryOpen,100)};[...document.querySelectorAll<HTMLButtonElement>('.admin-sidebar nav button')].find(b=>(b.textContent||'').trim()==='Pacientes')?.click();setTimeout(tryOpen,50)}
function renderDetail(host:HTMLElement,a:Appointment){let panel=host.querySelector<HTMLElement>('.gc-appointment-detail');if(!panel){panel=document.createElement('div');panel.className='gc-appointment-detail';host.querySelector('.gc-body')?.after(panel)}panel.innerHTML=`<div class="gc-appointment-main"><span class="section-kicker">Sessão na agenda</span><strong>${esc(a.full_name)}</strong><span>${esc(fmtDateTime(a.starts_at))} – ${esc(new Intl.DateTimeFormat('pt-BR',{hour:'2-digit',minute:'2-digit'}).format(new Date(a.ends_at)))}</span></div><div class="gc-appointment-info"><span><small>Status</small><strong>${esc(appointmentStatus(a))}</strong></span><span><small>Pagamento</small><strong>${a.paid_at?'Pago':'—'}</strong></span><span><small>Valor</small><strong>${esc(money(Number(a.amount_cents||0)))}</strong></span><span><small>Telefone</small><strong>${esc(a.phone||'—')}</strong></span><span><small>E-mail</small><strong>${esc(a.email||'—')}</strong></span></div><button type="button" class="gc-open-patient">Ver paciente</button>`;panel.querySelector<HTMLButtonElement>('.gc-open-patient')?.addEventListener('click',()=>findPatientCard(a.email))}
async function enrichGrid(grid:HTMLElement){if(grid.dataset.appointmentsBound==='1'||loading)return;grid.dataset.appointmentsBound='1';loading=true;try{const r=await fetch('/api/admin/session-management/appointments',{credentials:'include',cache:'no-store'});if(!r.ok)return;const data=await r.json().catch(()=>({})) as any;const appointments=(data.appointments||[]).filter((a:Appointment)=>['pending_payment','confirmed'].includes(String(a.status))&&a.workflow_state!=='awaiting_reschedule') as Appointment[];const byStart=new Map<string,Appointment>();for(const a of appointments)byStart.set(new Date(a.starts_at).toISOString(),a);const host=grid.closest<HTMLElement>('.google-calendar-admin');if(!host)return;grid.querySelectorAll<HTMLButtonElement>('.work-cell[data-cell]').forEach(cell=>{const starts=String(cell.dataset.cell||'').split('|')[0],a=byStart.get(starts);if(!a)return;cell.classList.add('has-appointment');cell.classList.remove('free','occupied','unset','blocked','held','confirmed');cell.classList.add(a.status==='confirmed'?'confirmed':'held');cell.dataset.appointmentId=String(a.id);cell.innerHTML=`<span class="gc-patient-name">${esc(a.full_name)}</span><small class="gc-patient-status">${esc(appointmentStatus(a))}</small>`;cell.addEventListener('click',()=>renderDetail(host,a))})}finally{loading=false}}
function scan(){document.querySelectorAll<HTMLElement>('.google-calendar-admin .work-grid').forEach(grid=>{grid.dataset.appointmentsBound='';void enrichGrid(grid)})}
export function installAdminAppointmentEnhancer(){const schedule=()=>{if(scheduled)clearTimeout(scheduled);scheduled=window.setTimeout(()=>{scheduled=undefined;scan()},120)};schedule();const root=document.getElementById('root');if(root)new MutationObserver(()=>schedule()).observe(root,{childList:true,subtree:true});window.addEventListener('pageshow',schedule)}
