import { FormEvent, useEffect, useMemo, useState } from 'react'
import {
  ArrowRight, CalendarDays, Check, ChevronLeft, CircleUserRound, Clock3, CreditCard,
  HeartHandshake, LayoutDashboard, LockKeyhole, LogOut, Menu, MessageCircle, Settings,
  ShieldCheck, Sparkles, Users, WalletCards, X,
} from 'lucide-react'
import { api } from './api-client'

type View = 'site' | 'login' | 'cadastro' | 'paciente' | 'admin-login' | 'admin'
type AdminTab = 'agenda' | 'pacientes' | 'configuracoes'
type GooglePending = { email: string; name: string; sub: string } | null
type Slot = { id: number; starts_at: string; ends_at: string; public_status?: 'free' | 'occupied'; status?: string; public_visibility?: string; source?: string; recurring_block_id?: string | null }

const money = (cents: number) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format((cents || 0) / 100)
const dateTime = (value: string) => new Intl.DateTimeFormat('pt-BR', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(value))
const timeOnly = (value: string) => new Intl.DateTimeFormat('pt-BR', { hour: '2-digit', minute: '2-digit' }).format(new Date(value))
const dayLabel = (value: string) => new Intl.DateTimeFormat('pt-BR', { weekday: 'long', day: '2-digit', month: 'long' }).format(new Date(value))
const statusText = (slot: Slot) => slot.status === 'confirmed' ? 'Consulta confirmada' : slot.status === 'held' ? 'Reserva aguardando pagamento' : slot.status === 'blocked' && slot.source === 'recurring_block' ? 'Bloqueio recorrente' : slot.status === 'blocked' ? 'Bloqueio manual' : slot.public_visibility === 'hidden' ? 'Oculto' : 'Livre'

function App({ initialView }: { initialView?: View }) {
  const params = new URLSearchParams(window.location.search)
  const googlePending: GooglePending = params.get('google-profile-required') === '1'
    ? { email: params.get('email') || '', name: params.get('name') || '', sub: params.get('sub') || '' }
    : null
  const [view, setView] = useState<View>(initialView || (googlePending ? 'cadastro' : 'site'))
  const [menuOpen, setMenuOpen] = useState(false)
  const navigate = (next: View) => { setView(next); setMenuOpen(false); window.scrollTo({ top: 0, behavior: 'smooth' }) }

  if (view === 'login' || view === 'cadastro') return <AuthView mode={view} googlePending={googlePending} onBack={() => navigate('site')} onSuccess={() => navigate('paciente')} onSwitch={navigate} />
  if (view === 'paciente') return <PatientView onBack={() => navigate('site')} />
  if (view === 'admin-login') return <AdminLogin onBack={() => { window.location.href='/' }} onSuccess={() => navigate('admin')} />
  if (view === 'admin') return <AdminView onBack={() => { window.location.href='/' }} />

  return <div className="site-shell">
    <header className="site-header">
      <button className="brand" onClick={() => navigate('site')}><span className="brand-mark">ψ</span><span><strong>Jacqueline Siqueira</strong><small>Psicologia • CRP 06/212470</small></span></button>
      <nav className={menuOpen ? 'nav open' : 'nav'}><a href="#sobre">Sobre</a><a href="#atendimento">Atendimento</a><a href="#como-funciona">Como funciona</a><a href="#duvidas">Dúvidas</a><button className="text-button" onClick={() => navigate('login')}>Área do paciente</button><button className="primary-button" onClick={() => navigate('login')}>Agendar consulta</button></nav>
      <button className="menu-button" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X size={22} /> : <Menu size={22} />}</button>
    </header>
    <main>
      <section className="hero"><div className="hero-copy"><span className="eyebrow">Psicoterapia com acolhimento e presença</span><h1>Um espaço seguro para compreender o que você sente e construir novos caminhos.</h1><p>Atendimento psicológico individual com escuta cuidadosa, ética e respeito ao seu tempo. Sessões exclusivamente online, com conforto, privacidade e segurança.</p><div className="hero-actions"><button className="primary-button large" onClick={() => navigate('login')}>Agendar consulta <ArrowRight size={18}/></button><a className="secondary-button" href="#sobre">Conheça o trabalho</a></div><div className="trust-row"><span><ShieldCheck size={18}/> Sigilo e ética profissional</span><span><CalendarDays size={18}/> Agendamento online</span></div></div><div className="hero-art"><div className="portrait-placeholder"><HeartHandshake size={52}/><span>Foto profissional</span></div></div></section>
      <section className="intro" id="sobre"><span className="section-kicker">Sobre a profissional</span><div className="split-heading"><h2>Psicoterapia é um encontro com a sua própria história.</h2><div><p>Este espaço será personalizado com a apresentação da psicóloga, sua abordagem, formação e forma de conduzir os atendimentos.</p><p>A proposta visual é transmitir acolhimento, segurança e profissionalismo.</p></div></div></section>
      <section className="services" id="como-funciona"><div className="section-title"><span className="section-kicker">Como funciona</span><h2>Como a Terapia Cognitivo-Comportamental pode ajudar</h2></div><div className="service-grid"><article><h3>O que é a TCC</h3><p>A Terapia Cognitivo-Comportamental é uma abordagem psicológica que considera a relação entre pensamentos, emoções e comportamentos, ajudando a compreender como esses elementos influenciam a forma de perceber e lidar com diferentes situações.</p></article><article><h3>Como funciona nas sessões</h3><p>Ao longo do processo terapêutico, psicóloga e paciente observam padrões de pensamento e comportamento, identificam dificuldades presentes e constroem novas formas de compreensão e enfrentamento de acordo com as necessidades de cada pessoa.</p></article><article><h3>Um processo individualizado</h3><p>O atendimento é conduzido de forma colaborativa e respeita a história, o ritmo e os objetivos de cada paciente. As sessões oferecem um espaço de escuta, reflexão e desenvolvimento de estratégias que possam contribuir para o bem-estar e a qualidade de vida.</p></article></div></section>
      <section className="process clinical-care-section" id="atendimento"><div className="section-title light"><span className="section-kicker">Atendimento</span><h2>Atendimento clínico individual</h2><p className="clinical-intro">O atendimento clínico individual é orientado pela Teoria Cognitivo-Comportamental (TCC) e acontece semanalmente em um horário fixo ou de acordo com a disponibilidade do paciente, com sessões online de 50 minutos.</p></div><div className="clinical-care-content"><div className="clinical-online-copy"><h3>Atendimento On-line</h3><p>O atendimento ocorre através da plataforma <strong>Google Meet</strong>, ambiente virtual acessível, seguro e confortável para os pacientes.</p></div></div></section>
      <section className="faq" id="duvidas"><div className="section-title"><span className="section-kicker">Dúvidas frequentes</span><h2>Perguntas frequentes</h2><p>Você tem alguma dúvida antes de marcar sua sessão?</p></div><div className="faq-grid"><details><summary>O que é psicoterapia?</summary><p>A psicoterapia é um processo de cuidado psicológico baseado em escuta profissional, reflexão e construção conjunta de estratégias para compreender emoções, pensamentos, comportamentos e dificuldades presentes na vida da pessoa.</p></details><details><summary>Como funciona a primeira consulta?</summary><p>A primeira consulta é um momento inicial de acolhimento e compreensão da demanda. A psicóloga conhece a história, as necessidades e os objetivos do paciente e explica como será conduzido o processo terapêutico.</p></details><details><summary>Quantas sessões são necessárias?</summary><p>Não existe um número fixo de sessões. A duração do acompanhamento depende das necessidades, objetivos e evolução de cada paciente ao longo do processo terapêutico.</p></details><details><summary>Os atendimentos são confidenciais?</summary><p>Sim. O atendimento psicológico é conduzido com respeito ao sigilo profissional e às normas éticas aplicáveis à atuação da psicóloga.</p></details><details><summary>O que faço se precisar cancelar ou remarcar uma sessão?</summary><p>Caso seja necessário cancelar ou remarcar, o paciente deve entrar em contato com antecedência para verificar a possibilidade de alteração do horário conforme a disponibilidade da profissional.</p></details><details><summary>Quais são as modalidades de atendimento disponíveis?</summary><p>Atualmente os atendimentos são realizados exclusivamente de forma on-line, por videochamada através do Google Meet.</p></details><details><summary>Atende crianças e adolescentes?</summary><p>O público atendido será informado conforme a atuação profissional e a disponibilidade da psicóloga.</p></details><details><summary>O que devo fazer se não me sentir à vontade com o terapeuta?</summary><p>É importante conversar sobre como você está se sentindo durante o processo. A relação terapêutica faz parte do atendimento e pode ser discutida de maneira aberta e respeitosa.</p></details><details><summary>Quanto tempo leva para ver resultados?</summary><p>Cada processo é único. Mudanças podem acontecer em ritmos diferentes, de acordo com a demanda, o envolvimento no acompanhamento e as características individuais de cada paciente.</p></details><details><summary>Como posso contatá-la para mais informações ou para agendar uma consulta?</summary><p>O agendamento pode ser realizado diretamente pelo site. Para outras informações, utilize os canais de contato disponibilizados pela profissional.</p></details></div></section>
    </main>
    <footer><div className="brand footer-brand"><span className="brand-mark">ψ</span><span><strong>Jacqueline Siqueira</strong><small>Psicologia • CRP 06/212470</small></span></div><p>© 2026 • Atendimento psicológico com ética, acolhimento e confidencialidade.</p><button className="admin-link" onClick={() => window.location.href='/admin'}>Acesso profissional</button></footer>
  </div>
}

function AuthView({ mode, googlePending, onBack, onSuccess, onSwitch }: { mode: 'login' | 'cadastro'; googlePending: GooglePending; onBack: () => void; onSuccess: () => void; onSwitch: (view: View) => void }) {
  const cadastro = mode === 'cadastro'; const [error,setError]=useState(''); const [loading,setLoading]=useState(false)
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');setLoading(true);const fd=new FormData(e.currentTarget);try{if(cadastro){const payload={full_name:String(fd.get('full_name')||''),birth_date:String(fd.get('birth_date')||''),cpf:String(fd.get('cpf')||''),phone:String(fd.get('phone')||''),email:String(fd.get('email')||''),password:String(fd.get('password')||''),google_sub:googlePending?.sub||''};if(googlePending)await api.completeGoogle(payload);else await api.register(payload)}else await api.login(String(fd.get('email')||''),String(fd.get('password')||''));onSuccess()}catch(err){setError(err instanceof Error?err.message:'Não foi possível entrar.')}finally{setLoading(false)}}
  return <div className="auth-page"><button className="back-link" onClick={onBack}><ChevronLeft size={18}/> Voltar ao site</button><div className="auth-card"><div className="auth-brand"><span className="brand-mark">ψ</span><div><strong>Jacqueline Siqueira</strong><small>Área do paciente</small></div></div><span className="section-kicker">{cadastro?'Novo paciente':'Bem-vindo(a)'}</span><h1>{cadastro?'Crie sua conta':'Acesse sua conta'}</h1>{!googlePending&&<button className="google-button" onClick={()=>window.location.href='/api/auth/google/start'}><span>G</span> Continuar com Google</button>}{!googlePending&&<div className="divider"><span>ou</span></div>}{error&&<div className="error-box">{error}</div>}<form onSubmit={submit}>{cadastro&&<><label>Nome completo<input name="full_name" required defaultValue={googlePending?.name||''}/></label><div className="form-row"><label>Nascimento<input name="birth_date" type="date" required/></label><label>CPF<input name="cpf" required/></label></div><label>Telefone<input name="phone" required/></label></>}<label>E-mail<input name="email" type="email" required defaultValue={googlePending?.email||''} readOnly={Boolean(googlePending)}/></label>{!googlePending&&<label>Senha<input name="password" type="password" minLength={8} required/></label>}<button className="primary-button full" disabled={loading}>{loading?'Aguarde...':cadastro?'Criar conta':'Entrar'}</button></form>{!googlePending&&<p className="auth-switch">{cadastro?'Já possui cadastro?':'Ainda não possui cadastro?'} <button onClick={()=>onSwitch(cadastro?'login':'cadastro')}>{cadastro?'Entrar':'Criar conta'}</button></p>}<small className="privacy-note"><LockKeyhole size={14}/> Seus dados serão tratados conforme a LGPD.</small></div></div>
}

function PatientView({ onBack }: { onBack: () => void }) {
  const [patient,setPatient]=useState<any>(null); const [slots,setSlots]=useState<Slot[]>([]); const [appointments,setAppointments]=useState<any[]>([]); const [price,setPrice]=useState(0); const [pixDiscount,setPixDiscount]=useState(0); const [selected,setSelected]=useState<number|null>(null); const [pendingAppointment,setPendingAppointment]=useState<number|null>(null); const [message,setMessage]=useState('')
  async function load(){try{const [me,av,ap]=await Promise.all([api.me(),api.availability(),api.myAppointments()]);setPatient(me.patient);setSlots(av.slots||[]);setPrice(Number(av.consultation_price_cents||0));setPixDiscount(Number(av.pix_discount_percent||0));setAppointments(ap.appointments||[])}catch{onBack()}}
  useEffect(()=>{load()},[])
  const groups=useMemo(()=>{const map=new Map<string,Slot[]>();slots.forEach(s=>{const k=dayLabel(s.starts_at);map.set(k,[...(map.get(k)||[]),s])});return [...map.entries()]},[slots])
  async function reserve(){if(!selected)return;try{const r=await api.reserve(selected);setPendingAppointment(r.appointment_id);setMessage('Horário reservado temporariamente. Escolha a forma de pagamento.');await load()}catch(err){setMessage(err instanceof Error?err.message:'Não foi possível reservar.')}}
  async function pay(method:'pix'|'card'){if(!pendingAppointment)return;try{const r=await api.checkout(pendingAppointment,method);if(r.checkout_url)window.location.href=r.checkout_url;else setMessage('Pagamento iniciado. Aguarde a confirmação automática.')}catch(err){setMessage(err instanceof Error?err.message:'Não foi possível iniciar o pagamento.')}}
  return <div className="patient-page"><header className="portal-header"><button className="brand" onClick={onBack}><span className="brand-mark">ψ</span><span><strong>Jacqueline Siqueira</strong><small>Área do paciente</small></span></button><div className="portal-user"><CircleUserRound size={21}/><span>{patient?.full_name||'Paciente'}</span><button className="text-button" onClick={async()=>{await api.logout();onBack()}}>Sair</button></div></header><main className="patient-content"><div className="patient-heading"><div><span className="section-kicker">Agendamento</span><h1>Escolha o melhor horário para você</h1><p>Horários indisponíveis aparecem apenas como <strong>Ocupado</strong>; o motivo é privado da profissional.</p></div><div className="price-card"><small>Valor da consulta</small><strong>{money(price)}</strong><span>{pixDiscount>0?`Pix com ${pixDiscount}% de desconto`:'Pix ou cartão'}</span></div></div>{message&&<div className="info-box">{message}</div>}<div className="availability-list">{groups.length===0&&<div className="empty-state">Ainda não há horários cadastrados.</div>}{groups.map(([day,items])=><section className="availability-day" key={day}><h2><CalendarDays size={19}/>{day}</h2><div className="time-grid">{items.map(slot=>{const free=slot.public_status==='free';return <button className={free?(selected===slot.id?'time selected':'time'):'time occupied'} key={slot.id} disabled={!free} onClick={()=>free&&setSelected(slot.id)}><Clock3 size={16}/>{timeOnly(slot.starts_at)}{free?(selected===slot.id?<Check size={16}/>:null):<span>Ocupado</span>}</button>})}</div></section>)}</div><aside className="booking-summary"><div><small>Horário escolhido</small><strong>{selected?dateTime(slots.find(s=>s.id===selected)?.starts_at||''):'Selecione um horário'}</strong></div><div><small>Consulta</small><strong>{money(price)}</strong></div>{pendingAppointment?<div className="payment-actions"><button className="primary-button" onClick={()=>pay('pix')}>Pix • Mercado Pago</button><button className="secondary-button" onClick={()=>pay('card')}>Cartão • InfinitePay</button></div>:<button className="primary-button" disabled={!selected} onClick={reserve}>Reservar horário <CreditCard size={17}/></button>}</aside><section className="my-appointments"><h2>Minhas consultas</h2>{appointments.length===0?<p className="empty-state">Nenhuma consulta cadastrada.</p>:appointments.map(a=><div className="appointment-row" key={a.id}><div><strong>{dateTime(a.starts_at)}</strong><small>{a.status==='confirmed'?'Confirmada':a.status==='pending_payment'?'Aguardando pagamento':a.status}</small></div><span>{money(a.amount_cents)}</span></div>)}</section></main></div>
}

function AdminLogin({onBack,onSuccess}:{onBack:()=>void;onSuccess:()=>void}){const[error,setError]=useState('');const[loading,setLoading]=useState(false);useEffect(()=>{api.adminMe().then(()=>onSuccess()).catch(()=>{})},[]);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');setLoading(true);const fd=new FormData(e.currentTarget);try{await api.adminLogin(String(fd.get('email')||''),String(fd.get('password')||''));onSuccess()}catch(err){setError(err instanceof Error?err.message:'Não foi possível entrar.')}finally{setLoading(false)}}return <div className="auth-page"><button className="back-link" onClick={onBack}><ChevronLeft size={18}/> Voltar ao site</button><div className="auth-card"><div className="auth-brand"><span className="brand-mark">ψ</span><div><strong>PsicoGestão</strong><small>Acesso profissional</small></div></div><span className="section-kicker">Área restrita</span><h1>Painel profissional</h1><p>Somente usuários autorizados podem acessar prontuários e anotações clínicas.</p>{error&&<div className="error-box">{error}</div>}<form onSubmit={submit}><label>E-mail<input name="email" type="email" autoComplete="username" required/></label><label>Senha<input name="password" type="password" autoComplete="current-password" required/></label><button className="primary-button full" disabled={loading}>{loading?'Entrando...':'Entrar'}</button></form></div></div>}

function AdminView({onBack}:{onBack:()=>void}){
  const[tab,setTab]=useState<AdminTab>('agenda');const[admin,setAdmin]=useState<any>(null);const[appointments,setAppointments]=useState<any[]>([]);const[patients,setPatients]=useState<any[]>([]);const[settings,setSettings]=useState<any>({});const[selectedPatient,setSelectedPatient]=useState<any>(null);const[patientDetail,setPatientDetail]=useState<any>(null);const[schedule,setSchedule]=useState<{slots:Slot[];recurring_blocks:any[]}>({slots:[],recurring_blocks:[]});const[message,setMessage]=useState('')
  async function load(){try{const[me,ap,ps,st,sc]=await Promise.all([api.adminMe(),api.adminAppointments(),api.adminPatients(),api.settings(),api.adminAvailability()]);setAdmin(me.admin);setAppointments(ap.appointments||[]);setPatients(ps.patients||[]);setSettings(st.settings||{});setSchedule({slots:sc.slots||[],recurring_blocks:sc.recurring_blocks||[]})}catch{window.location.href='/admin'}}
  useEffect(()=>{load()},[])
  async function openPatient(id:number){setSelectedPatient(id);setPatientDetail(await api.adminPatient(id))}
  async function addNote(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selectedPatient)return;const form=e.currentTarget;const fd=new FormData(form);try{await api.saveClinicalNote(selectedPatient,{session_date:String(fd.get('session_date')||''),note_text:String(fd.get('note_text')||'')});setPatientDetail(await api.adminPatient(selectedPatient));form.reset();setMessage('Anotação clínica salva.')}catch(err){setMessage(err instanceof Error?err.message:'Não foi possível salvar.')}}
  async function addSlot(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const fd=new FormData(form);try{await api.createSlot({starts_at:new Date(String(fd.get('starts_at'))).toISOString(),ends_at:new Date(String(fd.get('ends_at'))).toISOString()});form.reset();setMessage('Horário criado.');await load()}catch(err){setMessage(err instanceof Error?err.message:'Não foi possível criar.')}}
  async function addRecurring(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const fd=new FormData(form);const weekdays=String(fd.get('weekdays')||'').split(',').map(v=>Number(v.trim())).filter(v=>v>=0&&v<=6);try{await api.createRecurringBlock({weekdays,start_time:String(fd.get('start_time')||''),end_time:String(fd.get('end_time')||''),date_from:String(fd.get('date_from')||''),date_to:String(fd.get('date_to')||''),label:String(fd.get('label')||'Bloqueio recorrente')});form.reset();setMessage('Bloqueio recorrente criado. Para o paciente, esses horários aparecem como Ocupado.');await load()}catch(err){setMessage(err instanceof Error?err.message:'Não foi possível criar bloqueio recorrente.')}}
  async function saveSettings(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);try{await api.updateSettings({consultation_price_cents:Math.round(Number(fd.get('price')||0)*100),pix_discount_percent:Number(fd.get('pix_discount')||0),hold_minutes:Number(fd.get('hold_minutes')||15),appointment_duration_minutes:Number(fd.get('duration')||50)});setMessage('Configurações salvas.');await load()}catch(err){setMessage(err instanceof Error?err.message:'Não foi possível salvar.')}}
  const items:[any,string,AdminTab|null][]=[[LayoutDashboard,'Painel','agenda'],[Users,'Pacientes','pacientes'],[CalendarDays,'Agenda','agenda'],[HeartHandshake,'Consultas','agenda'],[WalletCards,'Pagamentos','agenda'],[MessageCircle,'Mensagens',null],[Settings,'Configurações','configuracoes']]
  return <div className="admin-page"><aside className="admin-sidebar"><div className="admin-logo"><span className="brand-mark">ψ</span><span><strong>PsicoGestão</strong><small>Painel profissional</small></span></div><nav>{items.map(([Icon,label,target])=><button key={label} className={target===tab?'active':''} disabled={!target} onClick={()=>target&&setTab(target)}><Icon size={17}/>{label}</button>)}</nav><button className="logout" onClick={async()=>{await api.adminLogout();window.location.href='/admin'}}><LogOut size={17}/> Sair</button></aside><main className="admin-main"><header className="admin-topbar"><div><span className="section-kicker">Gestão profissional</span><h1>{tab==='pacientes'?'Pacientes e prontuários':tab==='configuracoes'?'Configurações':'Agenda'}</h1></div><span className="admin-welcome">{admin?.display_name}</span></header>{message&&<div className="info-box">{message}</div>}
    {tab==='agenda'&&<><section className="admin-panel"><div className="admin-section-head"><div><h2>Novo horário</h2><p>Depois de criado, você pode deixá-lo livre, bloquear ou ocultar.</p></div></div><form className="inline-form" onSubmit={addSlot}><label>Início<input name="starts_at" type="datetime-local" required/></label><label>Fim<input name="ends_at" type="datetime-local" required/></label><button className="admin-primary">Adicionar</button></form></section>
    <section className="admin-panel"><div className="admin-section-head"><div><h2>Bloqueio recorrente</h2><p>Poderá usar <strong>bloqueio manual</strong>, <strong>bloqueio recorrente</strong>, <strong>ocultar horário</strong> ou liberar novamente. O bloqueio recorrente pode ser configurado por dias da semana e faixa de horário; quando a regra é desativada, os bloqueios futuros associados a ela são liberados novamente.</p></div></div><form className="inline-form" onSubmit={addRecurring}><label>Dias da semana<input name="weekdays" placeholder="1,2,3,4,5" required/><small>0=domingo, 1=segunda ... 6=sábado</small></label><label>Início<input name="start_time" type="time" required/></label><label>Fim<input name="end_time" type="time" required/></label><label>De<input name="date_from" type="date" required/></label><label>Até<input name="date_to" type="date" required/></label><label>Nome<input name="label" defaultValue="Horário ocupado"/></label><button className="admin-primary">Criar regra</button></form><div className="appointment-list">{schedule.recurring_blocks.map(r=><article className="admin-appointment" key={r.id}><div><strong>{r.label}</strong><span>Dia {r.weekday} • {r.start_time}–{r.end_time}</span><small>{r.date_from} até {r.date_to}</small></div><button className="secondary-button" onClick={async()=>{await api.setRecurringBlockActive(r.id,!r.active);await load()}}>{r.active?'Desativar e liberar':'Ativar'}</button></article>)}</div></section>
    <section className="admin-panel"><div className="admin-section-head"><h2>Grade administrativa</h2><span>{schedule.slots.length} horários</span></div><div className="appointment-list">{schedule.slots.map(s=><article className="admin-appointment" key={s.id}><div><strong>{dateTime(s.starts_at)}</strong><span>{statusText(s)}</span><small>Paciente verá: {s.public_visibility==='hidden'?'não aparece':s.status==='free'?'Livre':'Ocupado'}</small></div><div className="payment-actions">{s.status==='free'&&<button className="secondary-button" onClick={async()=>{await api.setSlotMode(s.id,'blocked');await load()}}>Bloquear</button>}{s.status==='blocked'&&<button className="secondary-button" onClick={async()=>{await api.setSlotMode(s.id,'free');await load()}}>Liberar</button>}{s.public_visibility==='hidden'?<button className="secondary-button" onClick={async()=>{await api.setSlotMode(s.id,'visible');await load()}}>Mostrar</button>:!['held','confirmed'].includes(String(s.status))&&<button className="secondary-button" onClick={async()=>{await api.setSlotMode(s.id,'hidden');await load()}}>Ocultar</button>}</div></article>)}</div></section></>}
    {tab==='pacientes'&&<div className="admin-content-grid"><section className="admin-panel patient-list"><div className="admin-section-head"><h2>Banco de pacientes</h2><span>{patients.length}</span></div>{patients.map(p=><button className={selectedPatient===p.id?'patient-card active':'patient-card'} key={p.id} onClick={()=>openPatient(p.id)}><strong>{p.full_name}</strong><span>{p.email}</span><small>{p.phone} • {p.appointment_count} atendimento(s)</small></button>)}</section><section className="admin-panel record-panel">{!patientDetail?<div className="empty-state">Selecione um paciente para abrir o prontuário.</div>:<><div className="record-head"><div><span className="section-kicker">Prontuário privado</span><h2>{patientDetail.patient.full_name}</h2><p>{patientDetail.patient.email} • {patientDetail.patient.phone}<br/>Nascimento: {patientDetail.patient.birth_date} • CPF: {patientDetail.patient.cpf}</p></div><LockKeyhole size={22}/></div><div className="record-warning">Estas anotações são exclusivas da área profissional. O paciente não possui acesso.</div><form className="admin-form" onSubmit={addNote}><label>Data da sessão<input name="session_date" type="date" required/></label><label>Observações clínicas<textarea name="note_text" required rows={6}/></label><button className="admin-primary">Salvar anotação</button></form><div className="note-list"><h3>Histórico de anotações</h3>{patientDetail.clinical_notes.length===0?<p className="empty-state">Nenhuma anotação registrada.</p>:patientDetail.clinical_notes.map((n:any)=><article key={n.id}><strong>{n.session_date}</strong><p>{n.note_text}</p><small>Registrado em {dateTime(n.created_at)}</small></article>)}</div></>}</section></div>}
    {tab==='configuracoes'&&<section className="admin-panel settings-panel"><h2>Atendimento e cobrança</h2><form className="admin-form" onSubmit={saveSettings}><label>Valor da consulta (R$)<input name="price" type="number" min="0" step="0.01" defaultValue={Number(settings.consultation_price_cents||0)/100}/></label><label>Desconto no Pix (%)<input name="pix_discount" type="number" min="0" max="100" step="0.1" defaultValue={settings.pix_discount_percent||0}/></label><label>Duração padrão (minutos)<input name="duration" type="number" min="10" defaultValue={settings.appointment_duration_minutes||50}/></label><label>Tempo de reserva aguardando pagamento (minutos)<input name="hold_minutes" type="number" min="5" defaultValue={settings.hold_minutes||15}/></label><button className="admin-primary">Salvar configurações</button></form></section>}
  </main></div>
}

export default App