type VaultConfig={configured:boolean;wrapped_vault_key?:string;wrap_iv?:string;kdf_salt?:string;kdf_iterations?:number;version?:string}
type EncryptedNote={note_ciphertext:string;note_iv:string;wrapped_dek:string;wrap_iv:string;encryption_version:string}

const enc=new TextEncoder(),dec=new TextDecoder(),VERSION='e2e-aes-256-gcm-v1',ITERATIONS=600000
let installed=false
let vaultKey:CryptoKey|null=null
let vaultPromise:Promise<CryptoKey>|null=null
const nativeFetch=window.fetch.bind(window)

function b64(bytes:Uint8Array){let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s)}
function unb64(v:string){const s=atob(v),a=new Uint8Array(s.length);for(let i=0;i<s.length;i++)a[i]=s.charCodeAt(i);return a}
async function derive(pass:string,salt:Uint8Array,iterations:number){const material=await crypto.subtle.importKey('raw',enc.encode(pass),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',hash:'SHA-256',salt,iterations},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}

function passwordDialog(title:string,description:string,confirm=false):Promise<string>{return new Promise((resolve,reject)=>{const overlay=document.createElement('div');overlay.style.cssText='position:fixed;inset:0;z-index:2147483647;background:rgba(8,18,28,.48);display:grid;place-items:center;padding:20px';const card=document.createElement('form');card.style.cssText='width:min(430px,100%);background:#fff;border-radius:18px;padding:24px;box-shadow:0 24px 70px rgba(0,0,0,.22);font:14px/1.45 system-ui,sans-serif;color:#17212b';card.innerHTML=`<h2 style="margin:0 0 8px;font-size:20px">${title}</h2><p style="margin:0 0 18px;color:#5a6875">${description}</p><label style="display:block;font-weight:600;margin-bottom:6px">Senha do cofre clínico</label><input data-p1 type="password" autocomplete="off" required minlength="12" style="box-sizing:border-box;width:100%;padding:11px 12px;border:1px solid #cbd5df;border-radius:10px;font:inherit">${confirm?'<label style="display:block;font-weight:600;margin:14px 0 6px">Confirmar senha</label><input data-p2 type="password" autocomplete="off" required minlength="12" style="box-sizing:border-box;width:100%;padding:11px 12px;border:1px solid #cbd5df;border-radius:10px;font:inherit">':''}<div data-error style="min-height:20px;color:#a42828;margin-top:8px"></div><div style="display:flex;justify-content:flex-end;gap:10px;margin-top:8px"><button data-cancel type="button" style="padding:10px 14px;border:0;background:#eef2f6;border-radius:9px">Cancelar</button><button type="submit" style="padding:10px 14px;border:0;background:#1d5f91;color:white;border-radius:9px">${confirm?'Criar cofre':'Abrir cofre'}</button></div>`;overlay.appendChild(card);document.body.appendChild(overlay);const p1=card.querySelector<HTMLInputElement>('[data-p1]')!,p2=card.querySelector<HTMLInputElement>('[data-p2]'),err=card.querySelector<HTMLElement>('[data-error]')!;setTimeout(()=>p1.focus(),0);card.querySelector('[data-cancel]')?.addEventListener('click',()=>{overlay.remove();reject(new Error('Cofre clínico não desbloqueado.'))});card.addEventListener('submit',e=>{e.preventDefault();const a=p1.value,b=p2?.value||a;if(a.length<12){err.textContent='Use pelo menos 12 caracteres.';return}if(a!==b){err.textContent='As senhas não conferem.';return}overlay.remove();resolve(a)})})}

async function getConfig(){const r=await nativeFetch('/api/admin/clinical-vault',{credentials:'include',cache:'no-store'});const d=await r.json().catch(()=>({})) as any;if(!r.ok)throw new Error(d.message||'Não foi possível acessar o cofre clínico.');return d as VaultConfig}
async function createVault(){const pass=await passwordDialog('Criar cofre clínico','Crie uma senha exclusiva para os prontuários. Ela não é enviada ao servidor e será necessária em outros computadores.',true);const raw=crypto.getRandomValues(new Uint8Array(32)),salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),wrapKey=await derive(pass,salt,ITERATIONS),wrapped=await crypto.subtle.encrypt({name:'AES-GCM',iv},wrapKey,raw);const r=await nativeFetch('/api/admin/clinical-vault',{method:'POST',credentials:'include',cache:'no-store',headers:{'content-type':'application/json'},body:JSON.stringify({wrapped_vault_key:b64(new Uint8Array(wrapped)),wrap_iv:b64(iv),kdf_salt:b64(salt),kdf_iterations:ITERATIONS,version:VERSION})});const d=await r.json().catch(()=>({})) as any;if(!r.ok)throw new Error(d.message||'Não foi possível criar o cofre clínico.');const key=await crypto.subtle.importKey('raw',raw,{name:'AES-GCM'},false,['encrypt','decrypt']);raw.fill(0);return key}
async function unlock(config:VaultConfig){const pass=await passwordDialog('Abrir cofre clínico','Digite a senha do cofre para visualizar, salvar ou exportar prontuários.');try{const salt=unb64(String(config.kdf_salt)),iv=unb64(String(config.wrap_iv)),wrapKey=await derive(pass,salt,Number(config.kdf_iterations||ITERATIONS)),raw=await crypto.subtle.decrypt({name:'AES-GCM',iv},wrapKey,unb64(String(config.wrapped_vault_key)));return crypto.subtle.importKey('raw',raw,{name:'AES-GCM'},false,['encrypt','decrypt'])}catch{throw new Error('Senha do cofre clínico incorreta.')}}
async function ensureVault(){if(vaultKey)return vaultKey;if(vaultPromise)return vaultPromise;vaultPromise=(async()=>{const cfg=await getConfig();vaultKey=cfg.configured?await unlock(cfg):await createVault();return vaultKey})().finally(()=>{vaultPromise=null});return vaultPromise}
async function encryptNote(text:string):Promise<EncryptedNote>{const vk=await ensureVault(),dek=await crypto.subtle.generateKey({name:'AES-GCM',length:256},true,['encrypt','decrypt']),noteIv=crypto.getRandomValues(new Uint8Array(12)),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv:noteIv},dek,enc.encode(text)),rawDek=new Uint8Array(await crypto.subtle.exportKey('raw',dek)),wrapIv=crypto.getRandomValues(new Uint8Array(12)),wrapped=await crypto.subtle.encrypt({name:'AES-GCM',iv:wrapIv},vk,rawDek);rawDek.fill(0);return{note_ciphertext:b64(new Uint8Array(cipher)),note_iv:b64(noteIv),wrapped_dek:b64(new Uint8Array(wrapped)),wrap_iv:b64(wrapIv),encryption_version:VERSION}}
async function decryptNote(n:any){const vk=await ensureVault();if(n.encryption_version!==VERSION)throw new Error('Prontuário usa uma versão de criptografia incompatível.');const raw=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(n.wrap_iv)},vk,unb64(n.wrapped_dek)),dek=await crypto.subtle.importKey('raw',raw,{name:'AES-GCM'},false,['decrypt']),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(n.note_iv)},dek,unb64(n.note_ciphertext));return dec.decode(plain)}
function urlInfo(input:RequestInfo|URL){try{return new URL(typeof input==='string'?input:input instanceof URL?input.href:input.url,location.origin)}catch{return null}}

export function installClinicalE2E(){if(installed)return;installed=true;window.fetch=async(input:RequestInfo|URL,init?:RequestInit)=>{const url=urlInfo(input),path=url?.pathname||'',method=(init?.method||(input instanceof Request?input.method:'GET')).toUpperCase();if(/^\/api\/admin\/patients\/\d+\/notes$/.test(path)&&method==='POST'&&init?.body){const original=JSON.parse(String(init.body));if(original.note_text){const envelope=await encryptNote(String(original.note_text));const body=JSON.stringify({session_date:original.session_date,appointment_id:original.appointment_id||null,...envelope});return nativeFetch(input,{...init,body,headers:{...(init.headers as any||{}),'content-type':'application/json'}})}}const openingClinical=/^\/api\/admin\/patients\/\d+$/.test(path)&&method==='GET'&&url?.searchParams.get('clinical')==='1';if(openingClinical)await ensureVault();const response=await nativeFetch(input,init);if(/^\/api\/admin\/patients\/\d+$/.test(path)&&method==='GET'&&response.ok){const data=await response.clone().json().catch(()=>null) as any;if(data&&Array.isArray(data.clinical_notes)){for(const note of data.clinical_notes)note.note_text=await decryptNote(note);return new Response(JSON.stringify(data),{status:response.status,statusText:response.statusText,headers:response.headers})}}return response} }
