import { FormEvent, useState } from 'react'

export default function PasswordRecovery(){
  const params=new URLSearchParams(location.search), token=params.get('token')||'', type=params.get('tipo')==='admin'?'admin':'patient'
  const[message,setMessage]=useState(''),[error,setError]=useState(''),[done,setDone]=useState(false)
  async function forgot(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');const fd=new FormData(e.currentTarget);const r=await fetch('/api/password/forgot',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:String(fd.get('email')||''),account_type:type})});const d=await r.json().catch(()=>({}));if(!r.ok){setError(d.message||'Não foi possível solicitar a recuperação.');return}setMessage(d.message||'Confira seu e-mail.')}
  async function reset(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');const fd=new FormData(e.currentTarget),password=String(fd.get('password')||''),confirm=String(fd.get('confirm')||'');if(password!==confirm){setError('As senhas não coincidem.');return}const r=await fetch('/api/password/reset',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({token,password})});const d=await r.json().catch(()=>({}));if(!r.ok){setError(d.message||'Não foi possível alterar a senha.');return}setDone(true);setMessage('Senha alterada com sucesso.')}
  return <div className="auth-page"><a className="back-link" href={type==='admin'?'/admin':'/'}>← Voltar</a><div className="auth-card"><div className="auth-brand"><span className="brand-mark">ψ</span><div><strong>PsicoGestão</strong><small>{type==='admin'?'Acesso profissional':'Área do paciente'}</small></div></div><span className="section-kicker">Recuperação de acesso</span><h1>{token?'Criar nova senha':'Esqueci minha senha'}</h1>{error&&<div className="error-box">{error}</div>}{message&&<div className="info-box">{message}</div>}{done?<a className="primary-button full" href={type==='admin'?'/admin':'/'}>Ir para o login</a>:token?<form onSubmit={reset}><label>Nova senha<input name="password" type="password" minLength={10} required/></label><label>Confirmar nova senha<input name="confirm" type="password" minLength={10} required/></label><button className="primary-button full">Alterar senha</button></form>:<><p>Informe o e-mail cadastrado. Enviaremos um link válido por 30 minutos.</p><form onSubmit={forgot}><label>E-mail<input name="email" type="email" required/></label><button className="primary-button full">Enviar link de recuperação</button></form></>}</div></div>
}
