type PatientTab='agenda'|'consultas'|'dados'|'seguranca'
let installed=false
let scheduled:number|undefined
let weekOffset=0
let selectedSlot:number|null=null
let heldAppointment:number|null=null

const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' }[c]||c))
const money=(cents:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format((Number(cents)||0)/100)
const mondayOf=(value:Date)=>{const d=new Date(value);d.setHours(0,0,0,0);const day=d.getDay();d.setDate(d.getDate()-(day===0?6:day-1));return d}
const addDays=(d:Date,n:number)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x}
const ymd=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`
const dateKey=(v:string)=>ymd(new Date(v))
const timeLabel=(v:string)=>new Intl.DateTimeFormat('pt-BR',{hour:'2-digit',minute:'2-digit'}).format(new Date(v))
const dateLabel=(v:string)=>new Intl.DateTimeFormat('pt-BR',{weekday:'long',day:'2-digit',month:'long',year:'numeric'}).format(new Date(v))
const shortDay=(d:Date)=>new Intl.DateTimeFormat('pt-BR',{weekday:'short'}).format(d).replace('.','')
const displayName=(name:string)=>{const p=String(name||'').trim().split(/\s+/).filter(Boolean);return p.length<=1?(p[0]||'Paciente'):p.length===2?p[0]:p.slice(0,-1).join(' ')}

async function request(path:string,init?:RequestInit){const r=await fetch(path,{credentials:'include',cache:'no-store',headers:{'content-type':'application/json',...(init?.headers||{})},...init});const d=await r.json().catch(()=>({})) as any;if(!r.ok)throw new Error(d.message||'Não foi possível concluir a solicitação.');return d}
function currentTab():PatientTab{const v=localStorage.getItem('patientPortalTab') as PatientTab|null;return v&&['agenda','consultas','dados','seguranca'].includes(v)?v:'agenda'}
function host(){let el=document.querySelector<HTMLElement>('.patient-stable-view');if(!el){el=document.createElement('main');el.className='patient-stable-view';document.body.appendChild(el)}return el}
function sidebar(){let el=document.querySelector<HTMLElement>('.patient-sidebar[data-native-safe="1"]');if(!el){el=document.createElement('aside');el.className='patient-sidebar';el.dataset.nativeSafe='1';el.innerHTML='<div class="patient-sidebar-brand"><span>Minha área</span><strong>Portal do paciente</strong><div class="patient-sidebar-welcome"></div></div><nav><button type="button" data-patient-tab="agenda">Agenda</button><button type="button" data-patient-tab="consultas">Minhas consultas</button><button type="button" data-patient-tab="dados">Meus dados</button><button type="button" data-patient-tab="seguranca">Segurança</button></nav><div class="patient-sidebar-foot"><small>Seus dados são privados e protegidos.</small></div>';document.body.appendChild(el)}return el}
function cleanup(){document.querySelector('.patient-stable-view')?.remove();document.querySelector('.patient-sidebar[data-native-safe="1"]')?.remove();document.documentElement.classList.remove('patient-portal-mounted')}
function setActive(tab:PatientTab){sidebar().querySelectorAll<HTMLButtonElement>('[data-patient-tab]').forEach(b=>b.classList.toggle('active',b.dataset.patientTab===tab));localStorage.setItem('patientPortalTab',tab)}

async function renderAgenda(){
 const h=host();h.innerHTML='<div class="patient-view-loading">Carregando agenda...</div>'
 try{
  const start=addDays(mondayOf(new Date()),weekOffset*7),end=addDays(start,4)
  const data=await request(`/api/availability?from=${encodeURIComponent(ymd(start))}&to=${encodeURIComponent(ymd(end))}`)
  const slots:any[]=data.slots||[];const byDay=new Map<string,any[]>();slots.forEach(s=>{const k=dateKey(s.starts_at);byDay.set(k,[...(byDay.get(k)||[]),s])})
  const pix=Number(data.pix_price_cents||data.consultation_price_cents||0),card=Number(data.card_price_cents||data.consultation_price_cents||0)
  const days=Array.from({length:5},(_,i)=>addDays(start,i))
  h.innerHTML=`<section class="patient-agenda-head"><span>Agendamento</span><h1>Escolha o melhor horário para você</h1><p>Selecione um horário disponível para reservar sua consulta.</p><div class="patient-week-nav"><button type="button" data-week-prev ${weekOffset<=0?'disabled':''}>‹</button><strong>${esc(new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric'}).format(start))}</strong><button type="button" data-week-next>›</button></div></section><section class="patient-week-grid">${days.map(d=>{const items=(byDay.get(ymd(d))||[]).sort((a,b)=>new Date(a.starts_at).getTime()-new Date(b.starts_at).getTime());return `<article class="patient-week-day"><header><strong>${d.getDate()}</strong><span>${esc(shortDay(d))}</span></header><div>${items.length?items.map(s=>{const free=s.public_status==='free'&&new Date(s.starts_at).getTime()>Date.now();return `<button type="button" class="patient-slot ${free?'free':'occupied'} ${selectedSlot===Number(s.id)?'selected':''}" data-slot-id="${s.id}" ${free?'':'disabled'}><span>${esc(timeLabel(s.starts_at))}</span><small>${free?'Disponível':'Ocupado'}</small></button>`}).join(''):'<p class="patient-no-slots">Sem horários</p>'}</div></article>`}).join('')}</section><aside class="patient-booking-box"><div><small>Horário escolhido</small><strong>${selectedSlot?esc(timeLabel(slots.find(s=>Number(s.id)===selectedSlot)?.starts_at||'')):'Selecione um horário'}</strong></div><div><small>Valores</small><strong>Pix: ${money(pix)} · Cartão: ${money(card)}</strong></div><div class="patient-booking-actions">${heldAppointment?'<button type="button" data-pay="pix">Pagar com Pix</button><button type="button" data-pay="card">Pagar com cartão</button>':`<button type="button" data-reserve ${selectedSlot?'':'disabled'}>Reservar horário</button>`}</div></aside><div class="patient-action-message" aria-live="polite"></div>`
  h.querySelector<HTMLButtonElement>('[data-week-prev]')?.addEventListener('click',()=>{if(weekOffset>0){weekOffset--;selectedSlot=null;heldAppointment=null;void renderAgenda()}})
  h.querySelector<HTMLButtonElement>('[data-week-next]')?.addEventListener('click',()=>{weekOffset++;selectedSlot=null;heldAppointment=null;void renderAgenda()})
  h.querySelectorAll<HTMLButtonElement>('[data-slot-id]').forEach(b=>b.addEventListener('click',()=>{selectedSlot=Number(b.dataset.slotId);heldAppointment=null;void renderAgenda()}))
  h.querySelector<HTMLButtonElement>('[data-reserve]')?.addEventListener('click',async()=>{if(!selectedSlot)return;const msg=h.querySelector<HTMLElement>('.patient-action-message')!;msg.textContent='Reservando horário...';try{const r=await request('/api/appointments/reserve',{method:'POST',body:JSON.stringify({slot_id:selectedSlot})});heldAppointment=Number(r.appointment_id);await renderAgenda()}catch(e){msg.textContent=e instanceof Error?e.message:'Não foi possível reservar.'}})
  h.querySelectorAll<HTMLButtonElement>('[data-pay]').forEach(b=>b.addEventListener('click',async()=>{if(!heldAppointment)return;const method=b.dataset.pay as 'pix'|'card';try{const r=await request('/api/payments/checkout',{method:'POST',body:JSON.stringify({appointment_id:heldAppointment,method})});if(r.checkout_url)window.location.href=r.checkout_url}catch(e){const msg=h.querySelector<HTMLElement>('.patient-action-message');if(msg)msg.textContent=e instanceof Error?e.message:'Não foi possível iniciar o pagamento.'}}))
 }catch(e){h.innerHTML=`<div class="patient-view-error">${esc(e instanceof Error?e.message:'Não foi possível carregar a agenda.')}</div>`}
}

async function renderConsultas(){const h=host();h.innerHTML='<div class="patient-view-loading">Carregando consultas...</div>';try{const d=await request('/api/appointments/mine');const a:any[]=d.appointments||[],now=Date.now();const ok=a.filter(x=>x.status==='confirmed');const future=ok.filter(x=>new Date(x.ends_at||x.starts_at).getTime()>=now).sort((x,y)=>new Date(x.starts_at).getTime()-new Date(y.starts_at).getTime());const hist=ok.filter(x=>new Date(x.ends_at||x.starts_at).getTime()<now).sort((x,y)=>new Date(y.starts_at).getTime()-new Date(x.starts_at).getTime());const row=(x:any)=>`<article class="patient-consult-row"><div><strong>${esc(dateLabel(x.starts_at))}</strong><span>${esc(timeLabel(x.starts_at))}</span></div><span>Confirmada</span></article>`;h.innerHTML=`<h1 class="patient-page-title">Minhas consultas</h1><section class="patient-panel"><div class="patient-panel-head"><strong>Próxima sessão</strong><small>Consultas confirmadas após pagamento</small></div>${future.length?future.map(row).join(''):'<p class="patient-empty">Você não possui consulta futura confirmada.</p>'}</section><section class="patient-panel"><div class="patient-panel-head"><strong>Histórico</strong><small>Sessões anteriores confirmadas</small></div>${hist.length?hist.map(row).join(''):'<p class="patient-empty">Ainda não há sessões anteriores no seu histórico.</p>'}</section>`}catch(e){h.innerHTML=`<div class="patient-view-error">${esc(e instanceof Error?e.message:'Não foi possível carregar suas consultas.')}</div>`}}

async function renderDados(){const h=host();try{const d=await request('/api/me'),p=d.patient||{};h.innerHTML=`<h1 class="patient-page-title">Meus dados</h1><section class="patient-panel"><form class="patient-form" data-profile><label>Nome completo<input name="full_name" value="${esc(p.full_name)}" required></label><label>Data de nascimento<input name="birth_date" type="date" value="${esc(p.birth_date)}" required></label><label>Telefone<input name="phone" value="${esc(p.phone)}" required></label><label>E-mail<input value="${esc(p.email)}" disabled></label><button type="submit">Salvar alterações</button><div class="patient-action-message"></div></form></section>`;h.querySelector<HTMLFormElement>('[data-profile]')?.addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget as HTMLFormElement,fd=new FormData(form),msg=form.querySelector<HTMLElement>('.patient-action-message')!;try{await request('/api/me/profile',{method:'PATCH',body:JSON.stringify({full_name:String(fd.get('full_name')||''),birth_date:String(fd.get('birth_date')||''),phone:String(fd.get('phone')||'')})});msg.textContent='Dados atualizados.'}catch(err){msg.textContent=err instanceof Error?err.message:'Não foi possível atualizar.'}})}catch(e){h.innerHTML=`<div class="patient-view-error">${esc(e instanceof Error?e.message:'Não foi possível carregar seus dados.')}</div>`}}

async function renderSeguranca(){const h=host();try{const d=await request('/api/me'),p=d.patient||{};h.innerHTML=`<h1 class="patient-page-title">Segurança</h1><div class="patient-security-grid"><section class="patient-panel"><h2>Alterar e-mail</h2><form class="patient-form" data-email><label>Novo e-mail<input name="email" type="email" value="${esc(p.email)}" required></label><label>Senha atual<input name="current_password" type="password" required></label><button type="submit">Alterar e-mail</button><div class="patient-action-message"></div></form></section><section class="patient-panel"><h2>Alterar senha</h2><form class="patient-form" data-password><label>Senha atual<input name="current_password" type="password" required></label><label>Nova senha<input name="new_password" type="password" minlength="10" required></label><label>Confirmar nova senha<input name="confirm_password" type="password" minlength="10" required></label><button type="submit">Alterar senha</button><div class="patient-action-message"></div></form></section></div>`;h.querySelector<HTMLFormElement>('[data-email]')?.addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget as HTMLFormElement,fd=new FormData(form),msg=form.querySelector<HTMLElement>('.patient-action-message')!;try{await request('/api/me/email',{method:'PATCH',body:JSON.stringify({email:String(fd.get('email')||''),current_password:String(fd.get('current_password')||'')})});msg.textContent='E-mail atualizado.'}catch(err){msg.textContent=err instanceof Error?err.message:'Não foi possível alterar o e-mail.'}});h.querySelector<HTMLFormElement>('[data-password]')?.addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget as HTMLFormElement,fd=new FormData(form),msg=form.querySelector<HTMLElement>('.patient-action-message')!,n=String(fd.get('new_password')||''),c=String(fd.get('confirm_password')||'');if(n!==c){msg.textContent='As novas senhas não coincidem.';return}try{await request('/api/me/password',{method:'PATCH',body:JSON.stringify({current_password:String(fd.get('current_password')||''),new_password:n})});msg.textContent='Senha alterada. Entre novamente com a nova senha.';form.reset()}catch(err){msg.textContent=err instanceof Error?err.message:'Não foi possível alterar a senha.'}})}catch(e){h.innerHTML=`<div class="patient-view-error">${esc(e instanceof Error?e.message:'Não foi possível carregar Segurança.')}</div>`}}

async function render(tab:PatientTab){if(!document.querySelector('.patient-page'))return;setActive(tab);if(tab==='agenda')await renderAgenda();else if(tab==='consultas')await renderConsultas();else if(tab==='dados')await renderDados();else await renderSeguranca()}
async function enhance(){const page=document.querySelector<HTMLElement>('.patient-page');if(!page){cleanup();return}document.documentElement.classList.add('patient-portal-mounted');page.classList.add('patient-native-shell');const main=page.querySelector<HTMLElement>('.patient-content');if(main)main.style.setProperty('display','none','important');sidebar();host();try{const d=await request('/api/me');const w=document.querySelector<HTMLElement>('.patient-sidebar-welcome');if(w)w.innerHTML=`Bem vindo, <strong>${esc(displayName(d.patient?.full_name||''))}</strong>`}catch{}await render(currentTab())}
export function installPatientPortalEnhancer(){if(installed)return;installed=true;document.addEventListener('click',e=>{const b=(e.target as HTMLElement|null)?.closest<HTMLButtonElement>('.patient-sidebar[data-native-safe="1"] [data-patient-tab]');if(!b)return;e.preventDefault();void render(b.dataset.patientTab as PatientTab)},true);const schedule=()=>{if(scheduled)clearTimeout(scheduled);scheduled=window.setTimeout(()=>{scheduled=undefined;void enhance()},80)};schedule();const root=document.getElementById('root');if(root)new MutationObserver(()=>schedule()).observe(root,{childList:true,subtree:false});window.addEventListener('pageshow',schedule)}
