import type { Env } from './types'

async function hasColumn(env: Env, table: string, column: string) { const result=await env.DB.prepare(`PRAGMA table_info(${table})`).all<any>(); return (result.results||[]).some((row:any)=>row.name===column) }
async function addColumn(env: Env, table:string,column:string,definition:string){if(!(await hasColumn(env,table,column)))await env.DB.prepare(`ALTER TABLE ${table} ADD COLUMN ${column} ${definition}`).run()}
let ready=false
export async function ensureSchema(env:Env){if(ready)return
await env.DB.exec(`PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS patients(id INTEGER PRIMARY KEY AUTOINCREMENT,full_name TEXT NOT NULL,birth_date TEXT NOT NULL,cpf TEXT NOT NULL UNIQUE,phone TEXT NOT NULL,email TEXT NOT NULL UNIQUE,password_hash TEXT,password_salt TEXT,google_sub TEXT UNIQUE,email_verified INTEGER NOT NULL DEFAULT 0,pricing_origin TEXT DEFAULT 'particular',portal_active INTEGER NOT NULL DEFAULT 1,portal_deleted_at TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS availability(id INTEGER PRIMARY KEY AUTOINCREMENT,starts_at TEXT NOT NULL,ends_at TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'free',public_visibility TEXT NOT NULL DEFAULT 'visible',source TEXT NOT NULL DEFAULT 'manual',recurring_block_id TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS recurring_blocks(id TEXT PRIMARY KEY,weekday INTEGER NOT NULL,start_time TEXT NOT NULL,end_time TEXT NOT NULL,date_from TEXT NOT NULL,date_to TEXT NOT NULL,label TEXT NOT NULL DEFAULT 'Bloqueio recorrente',active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS appointments(id INTEGER PRIMARY KEY AUTOINCREMENT,patient_id INTEGER NOT NULL,availability_id INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'pending_payment',amount_cents INTEGER NOT NULL DEFAULT 0,payment_method TEXT,payment_provider TEXT,payment_external_id TEXT,google_calendar_event_id TEXT,reserved_until TEXT,paid_at TEXT,confirmation_email_sent_at TEXT,cancellation_reason TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(patient_id) REFERENCES patients(id),FOREIGN KEY(availability_id) REFERENCES availability(id));
CREATE TABLE IF NOT EXISTS payments(id INTEGER PRIMARY KEY AUTOINCREMENT,appointment_id INTEGER NOT NULL,provider TEXT NOT NULL,external_id TEXT,method TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',amount_cents INTEGER NOT NULL,raw_reference TEXT,checkout_url TEXT,pix_qr_code TEXT,pix_copy_paste TEXT,raw_status TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(appointment_id) REFERENCES appointments(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS clinical_notes(id TEXT PRIMARY KEY,patient_id INTEGER NOT NULL,appointment_id INTEGER,author_admin_id TEXT NOT NULL,session_date TEXT NOT NULL,note_text TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS sessions(id TEXT PRIMARY KEY,patient_id INTEGER NOT NULL,token_hash TEXT NOT NULL UNIQUE,expires_at TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS admin_users(id TEXT PRIMARY KEY,email TEXT NOT NULL UNIQUE,password_hash TEXT NOT NULL,password_salt TEXT NOT NULL,display_name TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'psychologist',active INTEGER NOT NULL DEFAULT 1,totp_secret TEXT,totp_enabled INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS admin_sessions(id TEXT PRIMARY KEY,admin_user_id TEXT NOT NULL,token_hash TEXT NOT NULL UNIQUE,expires_at TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS password_reset_tokens(id TEXT PRIMARY KEY,account_type TEXT NOT NULL,account_id TEXT NOT NULL,token_hash TEXT NOT NULL UNIQUE,expires_at TEXT NOT NULL,used_at TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS oauth_pending(id TEXT PRIMARY KEY,token_hash TEXT NOT NULL UNIQUE,google_sub TEXT NOT NULL,email TEXT NOT NULL,full_name TEXT,expires_at TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS contact_messages(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,email TEXT NOT NULL,phone TEXT NOT NULL,message TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'new',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS audit_log(id TEXT PRIMARY KEY,actor_type TEXT NOT NULL,actor_id TEXT,action TEXT NOT NULL,entity_type TEXT NOT NULL,entity_id TEXT,metadata_json TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_admin_sessions_token_hash ON admin_sessions(token_hash);CREATE INDEX IF NOT EXISTS idx_audit_log_created_at ON audit_log(created_at DESC);CREATE INDEX IF NOT EXISTS idx_availability_starts_at ON availability(starts_at);CREATE INDEX IF NOT EXISTS idx_appointments_patient_id ON appointments(patient_id);CREATE INDEX IF NOT EXISTS idx_payments_appointment_id ON payments(appointment_id);`)
for(const [t,c,d] of [['patients','password_salt','TEXT'],['patients','email_verified','INTEGER NOT NULL DEFAULT 0'],['patients','portal_active','INTEGER NOT NULL DEFAULT 1'],['patients','portal_deleted_at','TEXT'],['appointments','amount_cents','INTEGER NOT NULL DEFAULT 0'],['appointments','reserved_until','TEXT'],['appointments','payment_method','TEXT'],['appointments','payment_provider','TEXT'],['appointments','payment_external_id','TEXT'],['appointments','google_calendar_event_id','TEXT'],['appointments','paid_at','TEXT'],['appointments','confirmation_email_sent_at','TEXT'],['appointments','cancellation_reason','TEXT'],['appointments','created_at','TEXT'],['appointments','updated_at','TEXT'],['payments','external_id','TEXT'],['payments','raw_reference','TEXT'],['payments','checkout_url','TEXT'],['payments','pix_qr_code','TEXT'],['payments','pix_copy_paste','TEXT'],['payments','raw_status','TEXT'],['payments','created_at','TEXT'],['payments','updated_at','TEXT'],['availability','public_visibility',"TEXT NOT NULL DEFAULT 'visible'"],['availability','source',"TEXT NOT NULL DEFAULT 'manual'"],['availability','recurring_block_id','TEXT'],['admin_users','totp_secret','TEXT'],['admin_users','totp_enabled','INTEGER NOT NULL DEFAULT 0']] as [string,string,string][])await addColumn(env,t,c,d)
await env.DB.prepare('UPDATE patients SET portal_active=1 WHERE portal_active IS NULL').run()
await env.DB.batch([['consultation_price_cents','0'],['pix_price_cents','0'],['card_price_cents','0'],['pix_discount_percent','0'],['timezone','America/Sao_Paulo'],['appointment_duration_minutes','50'],['hold_minutes','15']].map(([k,v])=>env.DB.prepare('INSERT OR IGNORE INTO settings (key,value) VALUES (?,?)').bind(k,v)))
ready=true}
